"""add password column to organizers

Revision ID: 102bd88dd5a6
Revises: 341179b55952
Create Date: 2023-11-30 20:55:57.691170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102bd88dd5a6'
down_revision = '341179b55952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
