"""add orgnizer foreign key to events table

Revision ID: cae97617f1af
Revises: e5f88363115a
Create Date: 2023-11-28 11:04:26.950526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae97617f1af'
down_revision = 'e5f88363115a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_organizer_id_organizers'), 'organizers', ['organizer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_organizer_id_organizers'), type_='foreignkey')
        batch_op.drop_column('organizer_id')

    # ### end Alembic commands ###
